tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/bundle'

brew 'antigen'
brew 'autojump'
brew 'bash'
brew 'node'
brew 'tree'
brew 'vim'
brew 'wget'
brew 'zsh'
brew 'watch'

brew 'youtube-dl'

brew 'gradle'

brew 'boot2docker'
brew 'docker'

brew 'caskroom/cask/brew-cask'
tap 'caskroom/versions'

cask 'font-inconsolata'
cask 'intellij-idea-ce'
cask 'iterm2'
cask 'java'
cask 'mou'
cask 'vagrant'
cask 'virtualbox'

cask 'google-chrome-canary'
cask 'skype'

#for resume generation
cask 'wkhtmltopdf'

cask 'omnigraffle'

#productivity - window and keyboards
cask 'hammerspoon'
cask 'karabiner'
cask 'seil'
